[dependencies]
reacher-core = { path = "./reacher-core" }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"